#!/bin/bash
echo "🚀 AI KNOWLEDGE NEXUS - QUICK START"
echo "===================================="
echo ""
echo "📦 Installing dependencies..."
npm install --legacy-peer-deps --quiet 2>&1 | grep -E "(added|removed)" || echo "Dependencies ready!"
echo ""
echo "✅ Installation complete!"
echo ""
echo "🎯 Available commands:"
echo "  npm run demo      - Run the epic demo"
echo "  npm run cli       - Interactive CLI interface"
echo "  npm start         - Start the API server"
echo "  npm test          - Run tests"
echo ""
echo "📚 Documentation:"
echo "  cat README.md           - Main documentation"
echo "  cat PROJECT_SUMMARY.md  - Complete project overview"
echo ""
